### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by Abdo99ab** [LBBO/netflix-migrate#44]
When I try to import profile data on the new account. No error is displayed. However the import doesn't work, viewing history stays the same as before the import.
Is there a solution for that?
![image](https://user-images.githubusercontent.com/28687391/87578758-cb05bb80-c6cc-11ea-833a-1f907864cac4.png)

**Comment by LBBO** [comment]
Duplicate of #31 

TL;DR: I haven't found a good way to do it yet. The data is exported already so it doesn't get lost, but the import is yet to be implemented.
